##Import Necessary Libraries

In [ ]:
!pip install tensorflow
!pip install scikit-learn==1.5.2
!pip install scikeras

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.35.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.82.1)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.15.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.12.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl (572.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 MB 884.7 kB/s eta 0:00:00
Downloading h5py-3.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 80.0 MB/s eta 0:00:00
Downloading keras-3.15.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 42.6 MB/s eta 0:00:00
Downloading protobuf-7.35.1-cp310-abi3-manylinux2014_x86_64.whl (327 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 327.1/327.1 kB 26.1 MB/s eta 0:00:00
Installing collected packages: protobuf, h5py, keras, tensorflow
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
  Attempting uninstall: h5py
    Found existing installation: h5py 3.16.0
    Uninstalling h5py-3.16.0:
      Successfully uninstalled h5py-3.16.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.20.0 requires tensorflow<2.21,>=2.20, but you have tensorflow 2.21.0 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.35.1 which is incompatible.
tensorflow-text 2.20.1 requires tensorflow<2.21,>=2.20.0, but you have tensorflow 2.21.0 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.35.1 which is incompatible.
ydf-tf 2.20.0 requires tensorflow==2.20.0, but you have tensorflow 2.21.0 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.35.1 which is incompatible.
Successfully installed h5py-3.14.0 keras-3.15.0 protobuf-7.35.1 tensorflow-2.21.0

Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (3.6.0)
Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 102.4 MB/s eta 0:00:00
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hdbscan 0.8.44 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Successfully installed scikit-learn-1.5.2

Collecting scikeras
  Using cached scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikeras) (3.15.0)
Requirement already satisfied: scikit-learn>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from scikeras) (1.5.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (26.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras>=3.2.0->scikeras) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Using cached scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

In [ ]:
!pip install scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikeras) (3.13.2)
Requirement already satisfied: scikit-learn>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from scikeras) (1.6.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (26.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras>=3.2.0->scikeras) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

In [ ]:
import pandas as pd
import numpy as np
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV,KFold
import warnings
warnings.filterwarnings('ignore')

###Load Data

In [ ]:
diabetes_data = pd.read_csv('diabetes.csv')
diabetes_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

##Data Preparation

In [ ]:
X = diabetes_data.drop(columns='Outcome')
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [ ]:
y = diabetes_data['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=13,shuffle=True,stratify=y)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

##Model Building

In [ ]:
def create_model(learning_rate=0.001,dropout_rate=0.0,activation_function='relu',init='glorot_uniform',neuron1=8,neuron2=4):

  model = Sequential([

    keras.layers.Input(shape=(8,)),
    Dense(neuron1, kernel_initializer=init, activation=activation_function),
    Dropout(dropout_rate),
    Dense(neuron2, kernel_initializer=init, activation=activation_function),
    Dropout(dropout_rate),
    Dense(1,activation='sigmoid')
  ])
  optimizer = keras.optimizers.Adam(learning_rate=learning_rate)
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
model = KerasClassifier(model=create_model,verbose=1)

In [ ]:
params_grid = {
    'model__learning_rate': [0.001,0.01],
    'model__dropout_rate': [0.0, 0.2],
    'model__activation_function': ['tanh','relu'],
    'model__init': ['glorot_uniform','he_uniform'],
    'model__neuron1': [8,16],
    'model__neuron2': [4,8],
    'batch_size':[10,20],
    'epochs':[10,50]
}

In [ ]:
kfold = KFold(n_splits=3,shuffle=True,random_state=45)
grid = GridSearchCV(estimator=model,param_grid=params_grid,cv=kfold,verbose=10,n_jobs=-1)

In [ ]:
grid_result = grid.fit(X_train,y_train)

Fitting 3 folds for each of 256 candidates, totalling 768 fits
Epoch 1/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4837 - loss: 0.8264
Epoch 2/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5277 - loss: 0.7471
Epoch 3/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5635 - loss: 0.6999
Epoch 4/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5814 - loss: 0.6544
Epoch 5/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6612 - loss: 0.6229
Epoch 6/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6547 - loss: 0.6388
Epoch 7/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6824 - loss: 0.5842
Epoch 8/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6889 - loss: 0.5876
Epoch 9/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6678 - loss: 0.6026
Epoch 10/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7003 - loss: 0.5693
Epoch 11/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6971 - loss: 0.5786
Epoch 12/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7101 - loss: 0.5426
Epoch 13/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7394 - loss: 0.5468
Epoch 14/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7085 - loss: 0.5597
Epoch 15/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7394 - loss: 0.5293
Epoch 16/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7003 - loss: 0.5449
Epoch 17/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7215 - loss: 0.5339
Epoch 18/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7199 - loss: 0.5447
Epoch 19/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7264 - loss: 0.5436
Epoch 20/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7378 - loss: 0.5345
Epoch 21/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7345 - loss: 0.5309
Epoch 22/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7541 - loss: 0.5074
Epoch 23/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7329 - loss: 0.5205
Epoch 24/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7313 - loss: 0.5126
Epoch 25/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7443 - loss: 0.5192
Epoch 26/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7068 - loss: 0.5560
Epoch 27/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7443 - loss: 0.5320
Epoch 28/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7296 - loss: 0.5172
Epoch 29/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7410 - loss: 0.5295
Epoch 30/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7215 - loss: 0.5292
Epoch 31/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7492 - loss: 0.5091
Epoch 32/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7606 - loss: 0.5031
Epoch 33/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7313 - loss: 0.5098
Epoch 34/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7378 - loss: 0.5242
Epoch 35/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7655 - loss: 0.4931
Epoch 36/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7459 - loss: 0.5053
Epoch 37/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7443 - loss: 0.5115
Epoch 38/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7671 - loss: 0.4937
Epoch 39/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7524 - loss: 0.5140
Epoch 40/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7443 - loss: 0.5239
Epoch 41/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7590 - loss: 0.5024
Epoch 42/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7524 - loss: 0.5159
Epoch 43/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7524 - loss: 0.4905
Epoch 44/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7378 - loss: 0.5093
Epoch 45/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7752 - loss: 0.5031
Epoch 46/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7573 - loss: 0.5083
Epoch 47/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7720 - loss: 0.4799
Epoch 48/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7606 - loss: 0.4896
Epoch 49/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7476 - loss: 0.5003
Epoch 50/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4941

In [ ]:
print(f'Best:{grid_result.best_score_:.6f} using {grid_result.best_params_}')
means = grid_result.cv_results_['mean_test_score']
stds =  grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean,std,param in zip(means,stds,params):
  print(f'{mean:.6f} ({std:.6f} with: {param}')

Best:0.775251 using {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.755715 (0.007502 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.762259 (0.021505 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.754097 (0.016219 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.771991 (0.008162 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.754105 (0.014565 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.767105 (0.001770 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.760617 (0.017872 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.752479 (0.017497 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.729659 (0.012436 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.726439 (0.025608 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.741081 (0.017742 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.736115 (0.018022 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.744333 (0.015596 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.755707 (0.003515 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.745967 (0.019458 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.770389 (0.015514 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.719823 (0.029836 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.757341 (0.011237 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.760617 (0.020747 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.757381 (0.025485 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.760609 (0.017057 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.755731 (0.015485 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.760601 (0.007512 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.762227 (0.018668 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.732935 (0.031915 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.742691 (0.018121 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.752431 (0.024454 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.747577 (0.014749 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.754073 (0.017933 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.749211 (0.010957 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.749203 (0.012463 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.754041 (0.013405 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.703698 (0.081044 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.742643 (0.034094 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.741001 (0.020483 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.742699 (0.028575 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.762219 (0.004354 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.752431 (0.013025 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.749195 (0.012612 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.762227 (0.018668 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.698757 (0.045817 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.745967 (0.019458 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.728017 (0.047824 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.736219 (0.051503 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.765487 (0.020912 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.732943 (0.026115 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.754073 (0.021914 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.752455 (0.007918 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.687382 (0.059098 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.697035 (0.046162 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.724821 (0.053790 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.726383 (0.055764 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.755723 (0.013984 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.741089 (0.025700 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.762243 (0.013531 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.771999 (0.011253 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.690634 (0.051574 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.679181 (0.028513 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.684091 (0.067529 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.716643 (0.020682 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.729627 (0.022819 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.742691 (0.014742 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.731325 (0.024348 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.745919 (0.022277 with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.768731 (0.017934 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.757349 (0.018137 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.770373 (0.017166 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.772007 (0.008702 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.718309 (0.040475 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.708465 (0.025953 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.721529 (0.061184 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.695417 (0.018773 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.747553 (0.006221 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.758959 (0.006004 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.763853 (0.005694 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.741065 (0.009985 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.724733 (0.018738 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.701945 (0.007273 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})
0.713391 (0.025228 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4})
0.698796 (0.053630 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8})
0.757389 (0.027815 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4})
0.762243 (0.013531 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8})
0.768739 (0.005702 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4})
0.760609 (0.010029 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8})
0.749227 (0.017878 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4})
0.747593 (0.017487 with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8})

In [ ]:
results_df = pd.DataFrame(grid_result.cv_results_)
results_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_batch_size,param_epochs,param_model__activation_function,param_model__dropout_rate,param_model__init,param_model__learning_rate,param_model__neuron1,param_model__neuron2,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,7.904274,2.995943,0.374932,0.044022,10,10,tanh,0.0,glorot_uniform,0.001,8,4,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.756098,0.746341,0.764706,0.755715,0.007502,81
1,4.165514,0.666762,0.423844,0.126641,10,10,tanh,0.0,glorot_uniform,0.001,8,8,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.760976,0.736585,0.789216,0.762259,0.021505,28
2,4.779909,0.757418,0.338984,0.057776,10,10,tanh,0.0,glorot_uniform,0.001,16,4,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.760976,0.731707,0.769608,0.754097,0.016219,90
3,4.945077,0.555143,0.470299,0.073361,10,10,tanh,0.0,glorot_uniform,0.001,16,8,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.780488,0.760976,0.774510,0.771991,0.008162,4
4,4.214599,0.475211,0.344527,0.075034,10,10,tanh,0.0,glorot_uniform,0.010,8,4,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.746341,0.741463,0.774510,0.754105,0.014565,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,10.672616,0.321428,0.292055,0.074788,20,50,relu,0.2,he_uniform,0.001,16,8,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.765854,0.707317,0.754902,0.742691,0.025410,163
252,10.686885,0.274966,0.357356,0.092738,20,50,relu,0.2,he_uniform,0.010,8,4,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.780488,0.712195,0.750000,0.747561,0.027934,141
253,9.633203,0.334156,0.428022,0.053811,20,50,relu,0.2,he_uniform,0.010,8,8,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.770732,0.736585,0.759804,0.755707,0.014238,82
254,10.730132,0.060691,0.293194,0.068520,20,50,relu,0.2,he_uniform,0.010,16,4,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.726829,0.692683,0.769608,0.729707,0.031470,190
255,10.803875,0.643396,0.317357,0.132179,20,50,relu,0.2,he_uniform,0.010,16,8,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.756098,0.721951,0.735294,0.737781,0.014051,177

In [ ]:
results_df.to_csv('results.csv')

In [ ]:
import sklearn
import tensorflow as tf
import keras
import scikeras

print("scikit-learn:", sklearn.__version__)
print("TensorFlow:", tf.__version__)
print("Keras:", keras.__version__)
print("SciKeras:", scikeras.__version__)

scikit-learn: 1.6.1
TensorFlow: 2.20.0
Keras: 3.13.2
SciKeras: 0.13.0

In [ ]:
print(model)
from sklearn.base import is_classifier

print(is_classifier(model))